source 'https://github.com/forestfsl/SegmentSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'SegmentView_Example' do
  pod 'SegmentView', :path => '../'
  pod 'Masonry'
  pod 'CTMediator'
  pod 'CTMediatoKit','~> 0.0.4'
  pod 'SLCategory', '~> 0.0.1'
#
#  target 'SegmentView_Tests' do
#    inherit! :search_paths
#
#
#  end
end


#target 'SegmentView' do
#   pod 'Masonry'
#   pod 'CTMediator'
#end
